version: '2.1'
orbs:
  node: circleci/node@4.2.1
jobs:
  vulnerabilities:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
          
      - run: npm install

      - run:
        name: Running k6 tests
        command: |-
          curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb
          sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
          rm google-chrome.deb

      - run: npm run vulnerabilities  

      - store_artifacts:
          path: /home/circleci/project/log-vulnerabilities.txt  
          destination: log-vulnerabilities
                  
  pentest:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      
      - run: npm install

      - run: npm run pentest  

      - store_artifacts:
          path: /home/circleci/project/log-pentest.txt 
          destination: pentest  

workflows:
  security_tests:
    jobs:
      - vulnerabilities
      - pentest